//! Widget Core - Comprehensive widget library for Arthropod GUI framework
//!
//! Provides a declarative widget API for building cross-platform user interfaces.
//! Integrates with Scene (hierarchy), ECS (components), Layout, and Text engines.
//!
//! # Widget Categories
//!
//! ## Primitive Widgets
//! - [`Text`] - Static or reactive text display
//! - [`Button`] - Clickable button with styles (primary, secondary, disabled)
//! - [`TextInput`] - Single-line text input with validation
//! - [`Checkbox`] - Boolean toggle with optional label
//! - [`ProgressBar`] - Visual indicator of completion progress
//! - [`Icon`] - Font or vector based icon
//! - [`Image`] - Bitmap image display
//!
//! ## Layout Widgets
//! - [`Row`] - Horizontal layout with alignment helpers
//! - [`Column`] - Vertical layout with alignment helpers
//! - [`Spacer`] - Flexible or fixed spacing between widgets
//! - [`Divider`] - Visual separator line (horizontal or vertical)
//! - [`Padding`] - Adds padding around a single child
//! - [`Center`] - Centers a child widget horizontally and/or vertically
//!
//! ## Advanced Layouts
//! - [`Stack`] - Overlay widgets with z-ordering
//! - [`Grid`] - 2D grid layout with fixed columns
//! - [`List`] - Dynamic list for runtime-generated content
//!
//! ## Container Widgets
//! - [`Container`] - Generic container with flexbox layout (legacy, prefer Row/Column)
//! - [`Card`] - Themed card with padding and background
//!
//! ## Form Widgets
//! - [`Form`] - Form with validation and submission
//!
//! # Widget Macros
//!
//! This crate provides declarative macros for common widgets, generated by `#[derive(Widget)]`.
//! These macros allow for a concise, Rust-like syntax for building UI trees.
//!
//! Each macro corresponds to a specific widget struct:
//!
//! | Macro | Widget Struct | Description |
//! |-------|---------------|-------------|
//! | `txt!` | [`Text`] | Display text (static or reactive). Supports special `@signal` syntax. |
//! | `btn!` | [`Button`] | Clickable button with styling flags (e.g., `primary`, `disabled`). |
//! | `col!` | [`Column`] | Vertical layout container for a list of children. |
//! | `row!` | [`Row`] | Horizontal layout container for a list of children. |
//! | `form!` | [`Form`] | Input form container with validation logic. |
//! | `input!` | [`TextInput`] | Text input field. |
//! | `progress_bar!` | [`ProgressBar`] | Progress indicator. |
//! | `icon!` | [`Icon`] | Vector or font icon. |
//! | `img!` | [`Image`] | Bitmap image. |
//!
//! ## Macro Syntax
//!
//! Macros generally follow the pattern:
//! `macro!(positional_arg, param1: value, param2: value, flag)`
//!
//! - **Positional**: First argument (if widget supports it, e.g., text content).
//! - **Parameters**: Key-value pairs (e.g., `size: 24.0`).
//! - **Flags**: Boolean flags (e.g., `primary`, `disabled`).
//! - **Callbacks**: Closures for events (e.g., `on_click: || println!("Hi")`).
//! - **Children**: List of child widgets (for containers like `col!` and `row!`).
//!
//! Note that when using `col!` or `row!`, children are passed as an array literal `[...]`
//! or a block that returns a [`WidgetTuple`].
//!
//! # Examples
//!
//! ## Using Macros (Recommended)
//!
//! ```no_run
//! use widget_core::{txt, btn, col, row, Spacer};
//!
//! // Text widget
//! let title = txt!("Hello World", size: 24.0);
//!
//! // Justified toolbar with spacer
//! let toolbar = row!([
//!     btn!("Back"),
//!     Spacer::flex(),  // Pushes remaining items to right
//!     btn!("Save", primary),
//!     btn!("Share", primary),
//! ], gap: 8.0);
//!
//! // Nested layouts
//! let layout = col!([
//!     txt!("Settings", size: 20.0),
//!     row!([btn!("OK"), btn!("Cancel")], gap: 8.0),
//! ], gap: 16.0, padding: 20.0);
//! ```
//!
//! ## Using Builder Pattern
//!
//! You can also construct widgets directly using the "Builder Pattern". This is more verbose
//! but explicit.
//!
//! ```no_run
//! use widget_core::{Text, Button, Row, Column, Center, Grid};
//!
//! // Text widget
//! let title = Text::new("Hello World").size(24.0);
//!
//! // Row layout with gap
//! // Note: Row::new takes a tuple of widgets (implementing WidgetTuple)
//! let row = Row::new((
//!     Button::new("Left"),
//!     Button::new("Center"),
//!     Button::new("Right"),
//! ))
//! .gap(10.0)
//! .padding(8.0);
//!
//! // Centered content
//! let centered = Center::new(Text::new("Centered!"));
//!
//! // Grid layout
//! let grid = Grid::new(
//!     (
//!         Text::new("A"), Text::new("B"),
//!         Text::new("C"), Text::new("D"),
//!     ),
//!     2, // columns
//! )
//! .gap(10.0);
//! ```
//!
//! # Custom Widgets
//!
//! To create your own widgets, implement the [`Widget`] trait:
//!
//! ```no_run
//! use widget_core::{Widget, WidgetContext, NodeContent, NodeId};
//!
//! struct MyWidget {
//!     label: String,
//! }
//!
//! impl Widget for MyWidget {
//!     fn build(&self, ctx: &mut WidgetContext) -> NodeId {
//!         // Create scene node, configure layout, register ECS components
//!         // For example, create an empty container:
//!         let node = ctx.create_node(ctx.root(), NodeContent::Empty);
//!         node
//!     }
//! }
//! ```
//!
//! See [`trait@Widget`] for a detailed guide and complete examples.

pub(crate) mod form;
pub(crate) mod layout;
pub(crate) mod layout_bridge;
pub(crate) mod primitive;

pub(crate) mod context;
pub(crate) mod input_state;
pub(crate) mod layer;
pub(crate) mod style;
pub(crate) mod widget_trait;

pub use context::WidgetContext;
pub use form::form::Form;
pub use input_state::{
    ComputedTextState, ReactiveColorState, ReactiveLayoutFlexGrowState, ReactiveLayoutWidthState,
    ReactiveTextState, TextInputState,
};
pub use layer::{Layer, LayerManager};
pub use layout::center::Center;
pub use layout::column::Column;
pub use layout::container::Container;
pub use layout::divider::Divider;
pub use layout::grid::Grid;
pub use layout::list::{list_from, List};
pub use layout::padding::Padding;
pub use layout::row::Row;
pub use layout::spacer::Spacer;
pub use layout::stack::Stack;
pub use layout_bridge::perform_layout;
pub use primitive::button::{Button, ButtonStyle};
pub use primitive::card::Card;
pub use primitive::carousel::Carousel;
pub use primitive::checkbox::Checkbox;
pub use primitive::icon::Icon;
pub use primitive::image::Image;
pub use primitive::progress_bar::ProgressBar;
pub use primitive::text::Text;
pub use primitive::text_input::TextInput;
pub use style::{Padding as StylePadding, ResolvedStyle, Style, StyleOverrides};
pub use widget_trait::{NamedWidgetTuple, Widget, WidgetTuple};

// Re-export layout types for advanced use cases (manual container construction)
pub use layout_engine::{FlexDirection, FlexStyle};
// Re-export node content for advanced use cases
pub use render_engine::{NodeContent, NodeId};
// Re-export theme types for theming support
pub use theme_engine::{Color as ThemeColor, TokenValue};
pub use theme_engine::{DesignTokens, SystemTheme};

// Re-export derive macros - Widget derive coexists with Widget trait (different namespaces)
pub use widget_macros::Widget;
pub use widget_macros::WidgetEnum;

// Re-export generated macros from this crate
// (txt!, btn!, col!, row!, input!, form! are defined via #[derive] and #[macro_export])

#[cfg(test)]
mod tests {
    #[test]
    fn test_widget_core_compiles() {
        // Sanity check that the crate compiles
    }
}
